### ISSUE TITLE
On friends, separate "liked back" and "not liked back" users

### ISSUE THREAD

**Issue by lazar-parker** [COSC481W-2021Winter/capstone-project-friend-match#124]
- [ ] Create two separate arrays on friends.php:
- - [ ] One for storing users who liked you back
- - [ ] One for storing users who didn't like you back
- [x] Sort the two sets on the page, with those who liked you back loading at the top

**Comment by sjiang1** [comment]
Reorganize the friends so that friends who liked you back will be shown on the page before other friends.
